
version: "3"
services:
  webshopdb:
    image: mongo
    container_name: "webshopdb"
    ports:
      - 27017:27017
  springboot-mongodb:
    image: springboot-mongodb:1.0
    container_name: springboot-mongodb
    ports:
      - 8080:8080
    links:
      - webshopdb